//#region source/constants/errors/input/statuses.js
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIGPATH_NOT_STRING */
const CONFIGPATH_NOT_STRING = "CONFIGPATH_NOT_STRING";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIGPATH_NOT_DOT_JS */
const CONFIGPATH_NOT_DOT_JS = "CONFIGPATH_NOT_DOT_JS";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_FILE_NOT_FOUND */
const CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_MODULE_NOT_RESOLVED */
const CONFIG_MODULE_NOT_RESOLVED = "CONFIG_MODULE_NOT_RESOLVED";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_PRE_INVALID */
const CONFIG_PRE_INVALID = "CONFIG_PRE_INVALID";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_NOT_OBJECT */
const CONFIG_NOT_OBJECT = "CONFIG_NOT_OBJECT";
new Set([CONFIG_NOT_OBJECT]);
//#endregion
export { CONFIGPATH_NOT_DOT_JS, CONFIGPATH_NOT_STRING, CONFIG_FILE_NOT_FOUND, CONFIG_MODULE_NOT_RESOLVED, CONFIG_NOT_OBJECT, CONFIG_PRE_INVALID };
