/* config error statuses */

/* statuses for static errors - libraries */

/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_INVALID */
export const LIBRARIES_INVALID = "LIBRARIES_INVALID";

// zod static error statuses

/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_NOT_RECORD */
export const LIBRARIES_NOT_RECORD = "LIBRARIES_NOT_RECORD";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_NOT_SUBKEY_CONFORM */
export const LIBRARIES_NOT_SUBKEY_CONFORM = "LIBRARIES_NOT_SUBKEY_CONFORM";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_RECORD_NOT_RECORDS */
export const LIBRARIES_RECORD_NOT_RECORDS = "LIBRARIES_RECORD_NOT_RECORDS";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_NOT_KEY_CONFORM */
export const LIBRARIES_NOT_KEY_CONFORM = "LIBRARIES_NOT_KEY_CONFORM";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS */
export const LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS =
  "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS */
export const LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS =
  "LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS";

// static error statuses arrays and sets

export const librariesStaticErrorStatuses = /** @type {const} */ ([
  LIBRARIES_NOT_RECORD,
  LIBRARIES_NOT_SUBKEY_CONFORM,
  LIBRARIES_RECORD_NOT_RECORDS,
  LIBRARIES_NOT_KEY_CONFORM,
  LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS,
  LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS,
]);
export const librariesStaticErrorStatusesSet = new Set(
  librariesStaticErrorStatuses,
);
