/* input error statuses */

/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIGPATH_NOT_STRING */
export const CONFIGPATH_NOT_STRING = "CONFIGPATH_NOT_STRING";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIGPATH_NOT_DOT_JS */
export const CONFIGPATH_NOT_DOT_JS = "CONFIGPATH_NOT_DOT_JS";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_FILE_NOT_FOUND */
export const CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_MODULE_NOT_RESOLVED */
export const CONFIG_MODULE_NOT_RESOLVED = "CONFIG_MODULE_NOT_RESOLVED";

/* statuses for static errors - config (pre) */

/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_PRE_INVALID */
export const CONFIG_PRE_INVALID = "CONFIG_PRE_INVALID";

// zod static error statuses

/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#INPUT#STATUSES#CONFIG_NOT_OBJECT */
export const CONFIG_NOT_OBJECT = "CONFIG_NOT_OBJECT";

// static error statuses arrays and sets

export const configPreStaticErrorStatuses = /** @type {const} */ ([CONFIG_NOT_OBJECT]);
export const configPreStaticErrorStatusesSet = new Set(configPreStaticErrorStatuses);
