//#region source/constants/errors/config/statuses.js
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_INVALID */
const LIBRARIES_INVALID = "LIBRARIES_INVALID";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_NOT_RECORD */
const LIBRARIES_NOT_RECORD = "LIBRARIES_NOT_RECORD";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_NOT_SUBKEY_CONFORM */
const LIBRARIES_NOT_SUBKEY_CONFORM = "LIBRARIES_NOT_SUBKEY_CONFORM";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_RECORD_NOT_RECORDS */
const LIBRARIES_RECORD_NOT_RECORDS = "LIBRARIES_RECORD_NOT_RECORDS";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_NOT_KEY_CONFORM */
const LIBRARIES_NOT_KEY_CONFORM = "LIBRARIES_NOT_KEY_CONFORM";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS */
const LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS = "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS";
/** $COMMENT#TSDOC#SRC#CONSTS#ERRORS#CONFIG#STATUSES#LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS */
const LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS = "LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS";
new Set([
	LIBRARIES_NOT_RECORD,
	LIBRARIES_NOT_SUBKEY_CONFORM,
	LIBRARIES_RECORD_NOT_RECORDS,
	LIBRARIES_NOT_KEY_CONFORM,
	LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS,
	LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS
]);
//#endregion
export { LIBRARIES_INVALID, LIBRARIES_NOT_KEY_CONFORM, LIBRARIES_NOT_RECORD, LIBRARIES_NOT_SUBKEY_CONFORM, LIBRARIES_RECORD_NOT_RECORDS, LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS, LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS };
