export declare const librariesCouldntZod: "The config's `libraries` key's value could not pass validation from zod.";
export declare const librariesShouldBeRecord: "The config `libraries` key's value, if provided, should only be a record (representing library keys paired with their selected variations).";
export declare const librariesMustSubKey: "The config `libraries` key's record has one or more keys that do not conform with the Comment Variables subkey (`COMMENTVARIABLES_SUBKEY`) format. This cannot happen when using a `libraryKey` obtained from a conform external library's resolved public Comment Variables data.";
export declare const librariesRecordMustBeRecords: "The config `libraries` key's record's values must only be records as well (representing Comment Variables keys from external libraries paired with their actual values).";
export declare const librariesMustKey: "The config `libraries` key's record's records' keys include one or more keys that do not conform with the Comment Variables key (`COMMENTVARIABLES#KEY`) format. This cannot happen when using a library variation `libraryVariations.<normalizedVariant>` obtained from a conform external library's resolved public Comment Variables data.";
export declare const librariesValuesMustBeStrings: "The config `libraries` key's record's records' values must only be strings (representing the actual values of the external libraries' Comment Variables keys these strings are paired with).";
export declare const librariesValuesCannotBeEmptyStrings: "The config `libraries` key's record's records' values cannot be empty strings.";
export declare const librariesStaticErrorMessages: readonly ["The config `libraries` key's value, if provided, should only be a record (representing library keys paired with their selected variations).", "The config `libraries` key's record has one or more keys that do not conform with the Comment Variables subkey (`COMMENTVARIABLES_SUBKEY`) format. This cannot happen when using a `libraryKey` obtained from a conform external library's resolved public Comment Variables data.", "The config `libraries` key's record's values must only be records as well (representing Comment Variables keys from external libraries paired with their actual values).", "The config `libraries` key's record's records' keys include one or more keys that do not conform with the Comment Variables key (`COMMENTVARIABLES#KEY`) format. This cannot happen when using a library variation `libraryVariations.<normalizedVariant>` obtained from a conform external library's resolved public Comment Variables data.", "The config `libraries` key's record's records' values must only be strings (representing the actual values of the external libraries' Comment Variables keys these strings are paired with).", "The config `libraries` key's record's records' values cannot be empty strings."];
export declare const librariesStaticErrorMessagesSet: Set<"The config `libraries` key's record has one or more keys that do not conform with the Comment Variables subkey (`COMMENTVARIABLES_SUBKEY`) format. This cannot happen when using a `libraryKey` obtained from a conform external library's resolved public Comment Variables data." | "The config `libraries` key's record's records' keys include one or more keys that do not conform with the Comment Variables key (`COMMENTVARIABLES#KEY`) format. This cannot happen when using a library variation `libraryVariations.<normalizedVariant>` obtained from a conform external library's resolved public Comment Variables data." | "The config `libraries` key's record's records' values cannot be empty strings." | "The config `libraries` key's record's records' values must only be strings (representing the actual values of the external libraries' Comment Variables keys these strings are paired with)." | "The config `libraries` key's record's values must only be records as well (representing Comment Variables keys from external libraries paired with their actual values)." | "The config `libraries` key's value, if provided, should only be a record (representing library keys paired with their selected variations).">;
