export const LIBRARIES_INVALID: "LIBRARIES_INVALID";
export const LIBRARIES_NOT_RECORD: "LIBRARIES_NOT_RECORD";
export const LIBRARIES_NOT_SUBKEY_CONFORM: "LIBRARIES_NOT_SUBKEY_CONFORM";
export const LIBRARIES_RECORD_NOT_RECORDS: "LIBRARIES_RECORD_NOT_RECORDS";
export const LIBRARIES_NOT_KEY_CONFORM: "LIBRARIES_NOT_KEY_CONFORM";
export const LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS: "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS";
export const librariesStaticErrorStatuses: readonly ["LIBRARIES_NOT_RECORD", "LIBRARIES_NOT_SUBKEY_CONFORM", "LIBRARIES_RECORD_NOT_RECORDS", "LIBRARIES_NOT_KEY_CONFORM", "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS"];
export const librariesStaticErrorStatusesSet: Set<"LIBRARIES_NOT_RECORD" | "LIBRARIES_NOT_SUBKEY_CONFORM" | "LIBRARIES_RECORD_NOT_RECORDS" | "LIBRARIES_NOT_KEY_CONFORM" | "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS">;
