export declare const LIBRARIES_INVALID = "LIBRARIES_INVALID";
export declare const LIBRARIES_NOT_RECORD = "LIBRARIES_NOT_RECORD";
export declare const LIBRARIES_NOT_SUBKEY_CONFORM = "LIBRARIES_NOT_SUBKEY_CONFORM";
export declare const LIBRARIES_RECORD_NOT_RECORDS = "LIBRARIES_RECORD_NOT_RECORDS";
export declare const LIBRARIES_NOT_KEY_CONFORM = "LIBRARIES_NOT_KEY_CONFORM";
export declare const LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS = "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS";
export declare const LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS = "LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS";
export declare const librariesStaticErrorStatuses: readonly ["LIBRARIES_NOT_RECORD", "LIBRARIES_NOT_SUBKEY_CONFORM", "LIBRARIES_RECORD_NOT_RECORDS", "LIBRARIES_NOT_KEY_CONFORM", "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS", "LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS"];
export declare const librariesStaticErrorStatusesSet: Set<"LIBRARIES_NOT_KEY_CONFORM" | "LIBRARIES_NOT_RECORD" | "LIBRARIES_NOT_SUBKEY_CONFORM" | "LIBRARIES_RECORD_NOT_RECORDS" | "LIBRARIES_RECORD_RECORDS_VALUES_EMPTY_STRINGS" | "LIBRARIES_RECORD_RECORDS_VALUES_NOT_STRINGS">;
